#!/usr/bin/python3
##
## EPITECH PROJECT, 2023
## 102architect
## File description:
## architect maths
##

import matrixes
import sys

def main():
    pass

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(e, file=sys.stderr)
        exit(84)
